### ISSUE TITLE
Request: Use tailwindcss

### ISSUE THREAD

**Issue by veritem** [Morncast/kigali-hacks#1]
the current css code is hard to mentains, naming is not that good. If you can allow, I can convert this [tailwindcss](https://tailwindcss.com/) which is more mentainable

**Comment by brunoblaise** [comment]
If possible you can go ahead.

**Comment by veritem** [comment]
We first need to have a design do the designs first

**Comment by brunoblaise** [comment]
I have the initial site designs I can send and you tell me how they look

**Comment by veritem** [comment]
sure please do

**Comment by veritem** [comment]
did you send designs?

**Comment by brunoblaise** [comment]
Yep I did
